//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTransaction
    {
        public int Id { get; set; }
        public string PaidMeduim { get; set; }
        public string AdditionalTransactionDetails { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> DateOfTransaction { get; set; }
        public string IpAddress { get; set; }
        public string SystemDetails { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> LastModifiedAt { get; set; }
        public string IsDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
