//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.CreditAccounts = new HashSet<CreditAccount>();
            this.CreditAccounts1 = new HashSet<CreditAccount>();
            this.FinancialTransactions = new HashSet<FinancialTransaction>();
            this.FinancialTransactions1 = new HashSet<FinancialTransaction>();
            this.GroupMembers = new HashSet<GroupMember>();
            this.GroupMembers1 = new HashSet<GroupMember>();
            this.GroupMembers2 = new HashSet<GroupMember>();
            this.Products = new HashSet<Product>();
            this.ProductRoles = new HashSet<ProductRole>();
            this.Groups = new HashSet<Group>();
            this.GroupProducts = new HashSet<GroupProduct>();
            this.GroupProducts1 = new HashSet<GroupProduct>();
            this.Groups1 = new HashSet<Group>();
            this.Groups2 = new HashSet<Group>();
            this.Products1 = new HashSet<Product>();
            this.ProductRoles1 = new HashSet<ProductRole>();
            this.LogHistories = new HashSet<LogHistory>();
            this.UserRoles = new HashSet<UserRole>();
            this.UserRoles1 = new HashSet<UserRole>();
            this.UserRoles2 = new HashSet<UserRole>();
            this.UsersAditionalInfoes = new HashSet<UsersAditionalInfo>();
            this.UsersAditionalInfoes1 = new HashSet<UsersAditionalInfo>();
            this.UsersAditionalInfoes2 = new HashSet<UsersAditionalInfo>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<CreditAccount> CreditAccounts { get; set; }
        public virtual ICollection<CreditAccount> CreditAccounts1 { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions1 { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual ICollection<GroupMember> GroupMembers1 { get; set; }
        public virtual ICollection<GroupMember> GroupMembers2 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductRole> ProductRoles { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<GroupProduct> GroupProducts { get; set; }
        public virtual ICollection<GroupProduct> GroupProducts1 { get; set; }
        public virtual ICollection<Group> Groups1 { get; set; }
        public virtual ICollection<Group> Groups2 { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<ProductRole> ProductRoles1 { get; set; }
        public virtual ICollection<LogHistory> LogHistories { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UserRole> UserRoles1 { get; set; }
        public virtual ICollection<UserRole> UserRoles2 { get; set; }
        public virtual ICollection<UsersAditionalInfo> UsersAditionalInfoes { get; set; }
        public virtual ICollection<UsersAditionalInfo> UsersAditionalInfoes1 { get; set; }
        public virtual ICollection<UsersAditionalInfo> UsersAditionalInfoes2 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
