//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditAccount
    {
        public int id { get; set; }
        public int pcanId { get; set; }
        public string usersSubscribed { get; set; }
        public int financialTransactionId { get; set; }
        public int productId { get; set; }
        public string productSubscriptionModel { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime toDate { get; set; }
        public int createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public int lastModifiedBy { get; set; }
        public System.DateTime lastModifiedAt { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual FinancialTransaction FinancialTransaction { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
