//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTransaction
    {
        public FinancialTransaction()
        {
            this.CreditAccounts = new HashSet<CreditAccount>();
        }
    
        public int id { get; set; }
        public string paidMedium { get; set; }
        public string additionalTransactionalDetails { get; set; }
        public double amount { get; set; }
        public System.DateTime dateOfTransaction { get; set; }
        public string ipAddress { get; set; }
        public string systemDetails { get; set; }
        public int createdBy { get; set; }
        public System.DateTime createdAt { get; set; }
        public int lastModifiedBy { get; set; }
        public System.DateTime lastModifiedAt { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual ICollection<CreditAccount> CreditAccounts { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
