//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int id { get; set; }
        public int groupId { get; set; }
        public int userId { get; set; }
        public bool isAdmin { get; set; }
        public int createdBy { get; set; }
        public System.DateTime createdAt { get; set; }
        public int lastModifiedBy { get; set; }
        public System.DateTime lastModifiedAt { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
