//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string token { get; set; }
        public string ipAddress { get; set; }
        public string systemDetails { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> lastModifiedAt { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
