//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupMembers = new HashSet<GroupMember>();
            this.GroupProducts = new HashSet<GroupProduct>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int groupOwner { get; set; }
        public int createdBy { get; set; }
        public System.DateTime createdAt { get; set; }
        public int lastModifiedBy { get; set; }
        public System.DateTime lastmodifiedAt { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual ICollection<GroupProduct> GroupProducts { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
