//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MembershipApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CreditAccounts = new HashSet<CreditAccount>();
            this.CreditAccounts1 = new HashSet<CreditAccount>();
            this.FinancialTransactions = new HashSet<FinancialTransaction>();
            this.FinancialTransactions1 = new HashSet<FinancialTransaction>();
            this.GroupMembers = new HashSet<GroupMember>();
            this.GroupMembers1 = new HashSet<GroupMember>();
            this.GroupMembers2 = new HashSet<GroupMember>();
            this.GroupProducts = new HashSet<GroupProduct>();
            this.GroupProducts1 = new HashSet<GroupProduct>();
            this.Groups = new HashSet<Group>();
            this.Groups1 = new HashSet<Group>();
            this.Groups2 = new HashSet<Group>();
            this.LogHistories = new HashSet<LogHistory>();
            this.ProductRoles = new HashSet<ProductRole>();
            this.ProductRoles1 = new HashSet<ProductRole>();
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.UserRoles = new HashSet<UserRole>();
            this.UserRoles1 = new HashSet<UserRole>();
            this.UserRoles2 = new HashSet<UserRole>();
        }
    
        public int id { get; set; }
        public string userId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string companyName { get; set; }
        public string address { get; set; }
        public string contactInfo { get; set; }
        public bool isOwner { get; set; }
        public bool status { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<int> lastModifiedBy { get; set; }
        public Nullable<System.DateTime> lastModifiedAt { get; set; }
        public string ipAddress { get; set; }
        public Nullable<System.DateTime> forgotPasswordRequestAt { get; set; }
        public string forgotPasswordToken { get; set; }
        public Nullable<System.DateTime> changeEmailRequestAt { get; set; }
        public string changeEmailToken { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual ICollection<CreditAccount> CreditAccounts { get; set; }
        public virtual ICollection<CreditAccount> CreditAccounts1 { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions1 { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual ICollection<GroupMember> GroupMembers1 { get; set; }
        public virtual ICollection<GroupMember> GroupMembers2 { get; set; }
        public virtual ICollection<GroupProduct> GroupProducts { get; set; }
        public virtual ICollection<GroupProduct> GroupProducts1 { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Group> Groups1 { get; set; }
        public virtual ICollection<Group> Groups2 { get; set; }
        public virtual ICollection<LogHistory> LogHistories { get; set; }
        public virtual ICollection<ProductRole> ProductRoles { get; set; }
        public virtual ICollection<ProductRole> ProductRoles1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UserRole> UserRoles1 { get; set; }
        public virtual ICollection<UserRole> UserRoles2 { get; set; }
    }
}
